dist: trusty
sudo: false
language: php
php:
- 7.0
- 5.6
- 7.1
- hhvm
- nightly
env:
  - GUZZLE=5
  - GUZZLE=6
matrix:
  allow_failures:
  - php: hhvm
  - php: nightly
services:
- redis-server
cache:
  directories:
  - vendor
before_install:
- PHP=$TRAVIS_PHP_VERSION
- if [ $PHP != 'hhvm' ] ; then echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini ; fi
- if [ $PHP != 'hhvm' ] && [ `php-config --vernum` -lt 70000 ]; then printf "yes\n" | pecl install -f apcu-4.0.10 ; fi
- if [ $PHP != 'hhvm' ] && [ `php-config --vernum` -ge 70000 ] ; then printf "yes\n" | pecl install -f apcu ; fi
- if [ $PHP != 'hhvm' ] ; then phpenv config-add ./tests/apc.ini; fi
before_script:
- composer config -g github-oauth.github.com $GITHUB_OAUTH_TOKEN
- if [ $GUZZLE == '5' ] ; then ./set_guzzle5.sh; fi
- if [ $PHP != 'nightly' ] && [ $PHP != '7.1' ]; then composer global require hirak/prestissimo; fi
- if [ $GUZZLE == '5' ] ; then composer update -o --prefer-dist --prefer-lowest; fi
- if [ $GUZZLE != '5' ] ; then composer install -o --prefer-dist; fi
script:
- ant phpcs-ci
- vendor/bin/phpunit --testsuite=unit
- if [ $PHP == '7.0' ] && [ $GUZZLE == '6' ] ; then vendor/bin/phpunit --testsuite=integration; fi
- ant behat
after_success:
- if [ $PHP == '5.6' ] && [ $GUZZLE == '6' ] ; then ./push-docs-to-gh-pages.sh; fi
notifications:
  hipchat:
    rooms:
      secure: VD5RvUZYVg1aokw8OeMhNfDPc39o2r4Jjq8s6U2QvMXzoiopHpj6+VYX1AHbhxMpBGmsgKfzbYQ6XfubJUeHq+FMzW3YEekwcyqXKCfWi5tLCE7Epb0dCySatztVTkqlXzXaAM6NhzdFxG6kQPiA9OcSvRPZmSwjuX4eYXRokRw=
  slack:
    secure: ZZ4PVXEv9FXuk81pRBCYAPZYeKnqvYYPd5DKB3E9WWKZQAZExMtSvqa7cDcbvQRk7jsD6E1RvTIn42p2jjypXN8ZKbmjsshrVd02fhmmwP7cQk9s3WE1fZhYt7CnCu0EJHOK3/fC3ddOXFJ/xlFvM3DXDd1RRZfBzVz5XWeQDr8=
